import { useEffect, useRef, useState } from "react";
import { Icon } from "./components/Icon";
import { Hero } from "./components/Hero";
import { QuoteForm } from "./components/QuoteForm";
import { ResultCard, EmptyState } from "./components/ResultCard";
import { MoneyChart } from "./components/MoneyChart";
import { ApproveStrip, Checklist, SecondQuoteCTA, FAQ, ScopeNote, Footer } from "./components/Sections";
import { BacklinkFooter } from "./components/BacklinkFooter";
import { evaluate, fmtMoney, REPAIRS, HISTORY, type EvalResult, type FormState } from "./lib/engine";

function buildSummary(form: FormState, result: EvalResult): string {
  const repair = REPAIRS[form.repair].label;
  const hist = HISTORY[form.history].label.toLowerCase();
  const lines = [
    "AC REPAIR QUOTE — SANITY CHECK",
    "--------------------------------",
    `System age:     ${form.age || "?"} years`,
    `Quoted repair:  ${repair}`,
    `Quote amount:   ${fmtMoney(form.quote)}`,
    `Performance:    ${hist}`,
    form.zip ? `ZIP:            ${form.zip}` : null,
    "",
    `VERDICT:  ${result.verdict.headline}`,
    `Risk:     ${result.risk}/100 (${result.verdict.band})`,
    `$5k rule: ${form.age || "?"} × ${fmtMoney(form.quote)} = ${fmtMoney(result.fiveK)}`,
    "",
    "Questions I'm asking before approving:",
    ...result.nextQuestions.map((q) => `  • ${q}`),
    "",
    "Generated by AC Quote Check — a quote sanity check, not a diagnosis.",
  ].filter(Boolean) as string[];
  return lines.join("\n");
}

function sampleSummary(): string {
  return [
    "AC REPAIR QUOTE — SANITY CHECK",
    "--------------------------------",
    "Run a check above and your summary will",
    "appear here, ready to copy and send to a",
    "second HVAC pro for a quick second opinion.",
  ].join("\n");
}

export default function App() {
  const [form, setForm] = useState<FormState>({
    age: "",
    quote: "",
    repair: "unsure",
    history: "unsure",
    zip: "",
  });
  const [result, setResult] = useState<EvalResult | null>(null);
  const [copied, setCopied] = useState(false);
  const toolRef = useRef<HTMLElement | null>(null);
  const resultRef = useRef<HTMLDivElement | null>(null);
  const hasResult = useRef(false);

  const setField = <K extends keyof FormState>(k: K, v: FormState[K]) =>
    setForm((f) => ({ ...f, [k]: v }));

  const submit = () => {
    const r = evaluate(form);
    hasResult.current = true;
    setResult(r);
    setCopied(false);
    // bring the freshly-computed result into view on mobile
    setTimeout(() => {
      if (window.innerWidth < 920 && resultRef.current) {
        const y = resultRef.current.getBoundingClientRect().top + window.scrollY - 16;
        window.scrollTo({ top: y, behavior: "smooth" });
      }
    }, 60);
  };

  // Live recalc: once the first result exists, any field change updates it silently
  // (no scroll, no button press). ZIP changes flow through too, but never block results.
  useEffect(() => {
    if (!hasResult.current) return;
    if (form.age === "" || form.quote === "" || Number(form.quote) <= 0) return;
    setResult(evaluate(form));
    setCopied(false);
  }, [form.age, form.quote, form.repair, form.history, form.zip]);

  const startTool = () => {
    if (toolRef.current) {
      const y = toolRef.current.getBoundingClientRect().top + window.scrollY - 20;
      window.scrollTo({ top: y, behavior: "smooth" });
    }
  };

  const summary = result ? buildSummary(form, result) : "";

  const copySummary = () => {
    if (!summary) return;
    const done = () => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2200);
    };
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(summary).then(done).catch(done);
    } else {
      done();
    }
  };

  return (
    <div className="page">
      <nav className="topnav">
        <div className="nav-inner">
          <div className="brand">
            <span className="brand-mark">
              <Icon name="shield" size={17} />
            </span>{" "}
            AC Quote Check
          </div>
          <div className="nav-tag">Check the math before you approve.</div>
        </div>
      </nav>

      <Hero onStart={startTool} />

      <main className="tool" ref={toolRef} id="tool">
        <ApproveStrip />
        <div className="tool-grid">
          <div className="tool-left">
            <QuoteForm form={form} setField={setField} onSubmit={submit} hasResult={!!result} />
          </div>
          <div className="tool-right" ref={resultRef}>
            {result ? (
              <ResultCard result={result} onCopy={copySummary} copied={copied} />
            ) : (
              <EmptyState />
            )}
          </div>
        </div>
      </main>

      <MoneyChart result={result} />
      <Checklist />
      <SecondQuoteCTA summary={summary || sampleSummary()} onCopy={copySummary} copied={copied} />
      <FAQ />
      <ScopeNote />
      <Footer />
      <BacklinkFooter />
    </div>
  );
}
